### ISSUE TITLE
New to Go, but would love to help

### ISSUE THREAD

**Issue by tonypnode** [RocketChat/Rocket.Chat.Go.SDK#16]
My team and I are looking to build some ChatOps integrations with our tools and RocketChat to compliment our SRE implementation.

Although I'm new to GO, I would love to be involved where I can. Do you have a board or a way for me to see where I might be able to help?

I thought I might start with some examples (as I figure them out :) )

**Comment by geekgonecrazy** [comment]
We definitely welcome your help!  

We don't currently have any sort of board.  This is mostly a labor of love by us golang fans :)

Feel free to join us in [#golangsdk](https://open.rocket.chat/channel/golangsdk)

**Comment by tonypnode** [comment]
didn't see this message. I joined in. closing issue
