### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DmitryPrischep** [RocketChat/Rocket.Chat.Go.SDK#36]
Could you please clarify what is the license of your project?

**Comment by jandd** [comment]
Without a proper license this SDK is not usable at all because the terms of usage/modification/redistribution/bundling are not known.

**Comment by phixom** [comment]
Which licence is used for this SDK? I would like to use it for my channelbot, but without licence it isn't possible.

**Comment by mickroll** [comment]
Please clarify your license, we can't use your project otherwise.
This only needs a few clicks, see this howto: https://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project#37895659

**Comment by geekgonecrazy** [comment]
Added
