### ISSUE TITLE
Inadequate random ID generation

### ISSUE THREAD

**Issue by jv283** [RocketChat/Rocket.Chat.Go.SDK#40]
There is problem with random ID's that are generated for every new message:
https://github.com/RocketChat/Rocket.Chat.Go.SDK/blob/e4a51dfb52e48e8cef8d2f96baa3db4b558ff8c8/realtime/client.go#L95-L97
The default precision for %f is 6 which means that it will take about 1178 new messages until there is less than 50% change that all generated random ID:s are unique.

Proposition: Either increase precision of %f in fmt.Sprintf, or implement more robust way to generate random ID:s.

**Comment by graywolf336** [comment]
Closed via #42
